### PR TITLE
Adding the5stars.org

### PR DESCRIPTION
**Pull request by ali-alhaidary**
the5stars.org

### CODE REVIEW

**Comment by ali-alhaidary** [comment]
@tibroc please.

**Comment by lkiesow** [comment]
Hi @ali-alhaidary, the location you provided is in the middle of the Black Sea. Could it be that you swapped longitude and latitude? 

Screenshot from 2021-12-04 00-40-55

**Comment by ali-alhaidary** [comment]
> Hi @ali-alhaidary, the location you provided is in the middle of the Black Sea. Could it be that you swapped longitude and latitude?
> 
> Screenshot from 2021-12-04 00-40-55

Hi @lkiesow , could be :-)
I will swap them...

**Comment by ali-alhaidary** [comment]
@lkiesow Now I think it is correct, however, there do exist on the web, but not in this file, an institute in the middle of the Caspian sea with the name 'Voronezh State Technical University'

**Comment by ali-alhaidary** [comment]
@lkiesow who can merge it please ?

**Comment by lkiesow** [comment]
Merging now…

> @lkiesow Now I think it is correct, however, there do exist on the web, but not in this file, an institute in the middle of the Caspian sea with the name 'Voronezh State Technical University'

Looks like the same problem you had. Pull request  #80 fixes that.

**Comment by ali-alhaidary** [comment]
@lkiesow thank you. I have put \n in the name so that it will be displayed as two lines, it displays correctly here in 'view file', however, it displays one single line after merging and accessing the site from internet http://bbbmap.uos.de/
Do you have any clue of why?
Screenshot 2021-12-04 at 18-06-14 bigbluebutton-map adopters geojson at a6a153691f94c64dbcd4889d80ff3440dc429efe · ali-alha
In here
Screenshot 2021-12-04 at 18-06-42 Screenshot
On the web

**Pull request merged**
